[platformio]
default_envs = automatic
src_dir = src

[env]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/shortbloke/Arduino_SNMP_Manager.git#8cc24ec
    powerbroker2/SafeString@^4.1.45
    https://github.com/Mottramlabs/MAX7219-7-Segment-Driver.git

[env:automatic]
build_src_filter =
    +<automatic/main.cpp>
    -<fixed-speeds/main.cpp>

[env:fixed-speeds]
build_src_filter =
    +<fixed-speeds/main.cpp>
    -<automatic/main.cpp>